### ISSUE TITLE
Doesn't reconnect

### ISSUE THREAD

**Issue by ryantollefson** [aegif/CmisSync#542]
I'm running Alfresco Community edition 5.0.d and CmisSync 2.3.3.0 on a Windows 7 Pro. machine (64 bit).  The Alfresco server is connected via LAN (https://192.168.x.x:xxxx) and reboots nightly.  The issue is the CmisSync client won't reconnect after the server reboots.  Every morning I have to exit the client and manually relaunch it.  Then it seems to work fine.

**Comment by nicolas-raoul** [comment]
Hello Ryan,
Thanks for the feedback!

There is a problem with the [icon staying in error even though network is actually back](https://github.com/aegif/CmisSync/issues/450), is it similar?

Did the sync really stop (not resume even after reconnecting)?
If yes, could you please post or send me your CmisSync log file?
CmisSync's log file can usually be found at C:\Users\nico\AppData\Roaming\cmissync\debug_log.txt (replace nico with your user name. Note: Configure Windows to show hidden files, otherwise you might not see AppData).

Thanks!
Nicolas

**Comment by ryantollefson** [comment]
Thanks for the info.  You are correct, after testing further I found it is still syncing, but icon shows error.
